### ISSUE TITLE
TypeScript Types?

### ISSUE THREAD

**Issue by drwpow** [robinweser/css-in-js-utils#9]
I recently discovered this utility library and love it! ❤️ Only problem is we use TypeScript, and this doesn’t ship types, and there doesn’t seem to be `@types/*` declarations, either.

How do you feel about converting this library to TypeScript in order to ship types? I only suggest that because these simple functions would be easy to convert (may not need many changes, if at all). And also it would prevent having to maintain TypeScript declarations independently of the code, which can be a pain if they diverge.

Would you like help with this? Possibly in a PR?

**Comment by robinweser** [comment]
If you'd be up to send a PR Id love that! I'm not using TypeScript myself and thus can't really help out with that.

Thanks for the love! Stay safe

**Comment by dangodev** [comment]
Just opened a PR. Would love some feedback: https://github.com/robinweser/css-in-js-utils/pull/10

Because this was a utility library, it was pretty painless! Only difference I saw was in one file (noted in the PR), Babel seemed to generate slightly-different compatibility wrappers. To me they all looked like surface-level changes that didn’t change support, but would love your 2nd opinion.
